### ISSUE TITLE
more examples

### ISSUE THREAD

**Issue by 0xtrzy** [tomolt/libschrift#1]
Please show example in vector
for example SDL draw lines

**Comment by tomolt** [comment]
I'm afraid I don't quite understand what you're saying, could you please elaborate a bit?
Do you mean I should give an example of how to use libschrift with SDL?
Or do you mean I should give an example of outputting a vector graphic instead of a bitmap graphic? Because the latter is not something libschrift is meant to do.

**Comment by maandree** [comment]
It may be interesting to split libschrift into two libraries: one library for rending rasters and one library for the rest, which could then be used for implementing other rendering methods such as to vector graphics.

**Comment by tomolt** [comment]
I'm sorry, but I'll have to close this issue,
since it is too vague to act upon and the original poster won't clarify.
Mattias' suggestion should probably be a separate issue anyway.
