### ISSUE TITLE
support anti-aliasing?

### ISSUE THREAD

**Issue by Shumpert820** [tomolt/libschrift#14]
I used your lib and render the demo on bmp picture, but my pic is not as clear as your x display. I can not figure out why this happen? Does x render support this function(anti-aliasing). 
Looking forward to your reply, thanks.
![test](https://user-images.githubusercontent.com/16200028/122739182-51e7ee80-d2b5-11eb-9940-6b81d25b58f7.png)

**Comment by tomolt** [comment]
Hi Shumpert820,

I guess this issue happens when you write out the .bmp file, after libschrift has already generated the image.
The reason I think that is because libschrift is supposed to always generate anti-aliased images -
you can't even turn anti-aliasing off if you wanted to.

Could it be that the .bmp file you write out has a color depth / bits per pixel value of 1?
Optimally, you should use a color depth of 8 bits per pixel, since that is the same color depth that libschrift uses.

Can you share some more information about how you write out the .bmp?
Do you use an image exporting library, or have you written it yourself?
Could you show me some code?
Another thing that might help is if you could send me the raw .bmp file, without converting it to .png.
Then I could take a look at the file header to find out which color depth is used.

**Comment by Shumpert820** [comment]
[Desktop.zip](https://github.com/tomolt/libschrift/files/6685984/Desktop.zip)
The pixel of bmp structure stored as three bits(R G B). I just fill the pixel with one fixed color. Maybe I don't know how to transform pixel from sft_render pixel(one byte)  to bmp pixel.
The attachment is my code. 
Thanks for your reply! LOL

**Comment by tomolt** [comment]
> The pixel of bmp structure stored as three bits(R G B). I just fill the pixel with one fixed color. Maybe I don't know how to transform pixel from sft_render pixel(one byte) to bmp pixel.

That is what I'm talking about - If you only use one bit per color channel per pixel, then your image can only have two different kinds of grayscale colors: black and white.
Anti-aliasing works by filling out the pixels at the edges with many different shades of gray.
Look at this zoomed-in picture of an anti-aliased alpha for example:
![antialiasing](https://user-images.githubusercontent.com/6959624/122751951-adec4c00-d290-11eb-8e9f-8eb8e39ecd88.png)
As you can see, this picture actually uses a lot more colors (shades of gray) than just black and white.
The solution is to use more bits per pixel. Instead of three, one for R G B each, you could use 24, which is 8 bits / 1 byte for R G B each.
Despite 'bmp' standing for 'bitmap', .bmp files can actually have any color depth, not just 1 bit per R G B.
You can even experiment with other color depths, like for example 4 bits for R G B each.
But you have to be aware that if you use less bits per pixel, the antialiasing will be worse.

UPDATE:
I've had a quick look at your .bmp file with a hex editor and it turns out that the image file you generate already has a color depth of 24 bits per pixel.
I recommend that you try the following: Instead of filling the pixels with a fixed color, take the byte that libschrift gives you and use that directly as your R value, and your G value, and your B value.

**Comment by Shumpert820** [comment]
Thank you. It works finally and the pic looks better than before.
<img width="579" alt="result" src="https://user-images.githubusercontent.com/16200028/122758103-ff193180-d2ca-11eb-9074-53fa7f621d8c.png">

**Comment by Shumpert820** [comment]
Sorry to bother one more time.  I changed the background color today. I found there are some strange lines with different colors around the characters. I just want to check whether this is unavoidable.
<img width="683" alt="test" src="https://user-images.githubusercontent.com/16200028/123254725-94adfe80-d521-11eb-8a06-e9c6b0ea48f9.png">

**Comment by tomolt** [comment]
It looks to me like you are computing the pixel color the following way:
```
if (value > 0) {
    pixel_color.red   = value;
    pixel_color.green = value;
    pixel_color.blue  = value;
} else {
    pixel_color = background_color;
}
```
This is not a good way to implement coloring, because it is responsible for the dark edges you are seeing.
The correct way is to use the values you get from libschrift as a so-called *alpha mask*,
which you can then use to *blend* between the foreground and background colors.
I strongly suggest you take some time learn about *alpha blending* (also called *compositing*), specifically with the *over* operator.
The short answer is that you should the following logic instead:
```
float alpha = value / 255.0;
pixel_color.red   = alpha * foreground_color.red   + (1.0 - alpha) * background_color.red;
pixel_color.green = alpha * foreground_color.green + (1.0 - alpha) * background_color.green;
pixel_color.blue  = alpha * foreground_color.blue  + (1.0 - alpha) * background_color.blue;
```
Basically, you have to linearly interpolate between the foreground and background colors.
This should be good enough for most purposes. But it's still not 100% correct.
First off, you can do slightly better by performing proper rounding.
Second, If you want perfect coloration even around the edges of the characters, you should also look into *gamma correction*.
Specifically, you will want to transform your foreground and background colors from *sRGB* colorspace to *linear RGB* colorspace beforehand,
perform the above calculation, and then transform the resulting pixel_value from *linear RGB* colorspace back to *sRGB* colorspace for display.
However, this should only be neccessary if you using this for a CGI application like a videogame, in which case you should really know about these things.

**Comment by Shumpert820** [comment]
Thank you very much. I looked for some materials for these. After performing simple alpha blending and gamma correction I finally get the pic without black lines.
<img width="580" alt="better" src="https://user-images.githubusercontent.com/16200028/123356828-00807d80-d59b-11eb-846a-1a2034ceca67.png">
