### ISSUE TITLE
Whitespaces are not being rendered

### ISSUE THREAD

**Issue by monstermichl** [tomolt/libschrift#26]
Hey tomolt, thanks for the great library. I'm encountering a problem that whitespaces are not being rendered for some reason. Did I miss something? I used your stress.c file as template.

Here's a snippet of my code. *letterImagePtr is just a struct that groups several image related information.*
```c
SFT sft = {0};
SFT_Glyph gid;
SFT_GMetrics *metricsPtr = &(letterImagePtr->metrics);
SFT_Image *imagePtr = &(letterImagePtr->image);

sft.font = font;
sft.xScale = size;
sft.yScale = size;
sft.flags = SFT_DOWNWARD_Y;

if (sft_lookup(&sft, c, &gid) < 0)
{
    /* Lookup failed. */
}
else if (sft_gmetrics(&sft, gid, metricsPtr) < 0)
{
    /* Metrics evaluation failed. */
}
else
{
    imagePtr->width  = metricsPtr->minWidth;
    imagePtr->height = metricsPtr->minHeight;
    imagePtr->pixels = malloc((size_t)imagePtr->width * (size_t)imagePtr->height);
    printf("\n-------> Char: '%c', width: %d\n", (const char)c, imagePtr->width);
    if (imagePtr->pixels)
    {
        sft_render(&sft, gid, *imagePtr);
    }
    else
    {
        /* Pixel reservation failed. */
    }
}
```

Here's the Output:
![image](https://user-images.githubusercontent.com/17982894/230347482-bfaa754d-a81d-43d6-b543-c08b087935b3.png)

Thanks and BR
monstermichl

**Comment by tomolt** [comment]
Hi,

The width of a glyph refers to how to big of a canvas/image is needed to draw the glyph into.
As there is nothing to be drawn for white space characters, it makes sense that the width ends up being zero.
What's more important is the glyphs "advanceWidth" attribute, which tells you how far you should move
your 'pen' to the right before drawing the next glyph.

I tried documenting what each of these attributes does in [the man page](https://tomolt.github.io/libschrift/v0.10.2.schrift.3.html).

Also, I admit that the stress program is really not a great reference, since it doesn't show you how to actually put
text on the screen (it is meant for performance profiling).
If you're vaguely familiar with X11 you might find the sftdemo program useful.

Alternatively, someone else wrote [another sample program](https://github.com/lhf/libschrift-show),
which writes out PGM images (instead of relying on a specific graphics API).
I have not looked closely at that one so far, but it is probably a good reference.

I hope this helps!

**Comment by monstermichl** [comment]
Great, thank you. I must have missed that :)
